# Generated by Django 5.2.6 on 2025-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_additionalsection_education_experience_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institutes/'),
        ),
        migrations.AddField(
            model_name='education',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
